POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Teste",
    "email": "teste@lab.com",
    "password": "Teste1234",
    "role": "mentor"
}

###

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Teste2",
    "email": "teste2@lab.com",
    "password": "Teste21234",
    "role": "admin"
}

###

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Teste3",
    "email": "teste3@lab.com",
    "password": "Teste31234",
    "role": "gestor"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "teste2@lab.com",
    "password": "Teste21234"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "teste3@lab.com",
    "password": "Teste31234"
}


###

POST http://localhost:3003/leaguers/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkOWI2OTMzLTcxZmItNGM5Mi1iYzVhLTFmZDRmOTliNDgzNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1MzUyMTA1MiwiZXhwIjoxNjUzNTIyODUyfQ.tU0ZQDN_RUR3kBfiG2u0srlmiwCyBlbwKW_vXAYuHZY

{
    "name": "Teste",
    "turma": "turma-piloto",
    "fase": "introducao"
}

###

POST http://localhost:3003/leaguers/create
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkOWI2OTMzLTcxZmItNGM5Mi1iYzVhLTFmZDRmOTliNDgzNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1MzU5MDkwOCwiZXhwIjoxNjUzNTkyNzA4fQ.O0v-9HZtzKlNnBZsyMgPOOddrWVHNqIj35EUqziG0jE

{
    "name": "Teste3",
    "turma": "turma-2",
    "fase": "labs",
    "responsavel": "Teste3"
}

###

GET http://localhost:3003/leaguers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkOWI2OTMzLTcxZmItNGM5Mi1iYzVhLTFmZDRmOTliNDgzNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1Mzk2MDY0MiwiZXhwIjoxNjUzOTY3ODQyfQ.QXYZXv3GZ1nDdCtRYpfnujVgTuA0eJk9LsxkQ6opzV4

###

PUT http://localhost:3003/user/role
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkOWI2OTMzLTcxZmItNGM5Mi1iYzVhLTFmZDRmOTliNDgzNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1MzcwMzYyOCwiZXhwIjoxNjUzNzA1NDI4fQ.oykFQo86xVJ0P-AbLpUi2ywYf-8fFob8IpIIrmJAlOI

{
    "userName": "Teste",
    "newRole": "admin"
}

###

GET http://localhost:3003/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1ODcwYjU1LTllY2ItNGRmOC04Mzg1LTI3ZmNhODhjMTBlZCIsInJvbGUiOiJnZXN0b3IiLCJpYXQiOjE2NTM2NzQ5NzMsImV4cCI6MTY1MzY3Njc3M30.8Vstn3P8AXVzhjWxXM2REwltlUbta5C-Ldn0RNwMv8M

###

PUT http://localhost:3003/leaguers/editfase
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkOWI2OTMzLTcxZmItNGM5Mi1iYzVhLTFmZDRmOTliNDgzNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1MzcwNzQ3NiwiZXhwIjoxNjUzNzE0Njc2fQ.0CzuULKwE2GBDixjh5FbcInCuhkgSHCyEf5dnkVyemo

{
    "leaguerId": "80b70ee8-010a-4be5-a40f-dee8a2162d9c",
    "newFase": "introducao"
}

###

PUT http://localhost:3003/user/password
Content-Type: application/json

{
    "email":"teste3@lab.com",
    "password":"Teste312345",
    "new_password":"Teste31234"
}

###

PUT http://localhost:3003/leaguers/edit
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1ODcwYjU1LTllY2ItNGRmOC04Mzg1LTI3ZmNhODhjMTBlZCIsInJvbGUiOiJnZXN0b3IiLCJpYXQiOjE2NTM3ODk2MTYsImV4cCI6MTY1Mzc5NjgxNn0.bmSsg5S2TaksK3fSHLslyJZXRyZwWmneByVYXcnI13M

{
    "id": "2516189c-c4af-4b7f-8259-d6f215720310",
    "name": "Teste3",
    "turma": "turma-2",
    "fase": "beta",
    "responsavel": "Teste"
}

###

POST http://localhost:3003/user/signup
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkOWI2OTMzLTcxZmItNGM5Mi1iYzVhLTFmZDRmOTliNDgzNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1NDExNzQ2MCwiZXhwIjoxNjU0MTI0NjYwfQ.N5YLpMHyUx_UcdWU28hvChrHDkDdjPEfLTyV3HyopVw

{
    "name": "Teste4",
    "email": "teste4@lab.com",
    "password": "Teste41234",
    "role": "adm"
}